# Generated by Django 4.1.5 on 2023-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Последние вакансии',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.FileField(upload_to='app/admin/demand')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.FileField(upload_to='app/admin/geography')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('general', models.TextField(verbose_name='General information')),
                ('scope', models.TextField(verbose_name='Scope application')),
                ('hard_skills', models.TextField(verbose_name='Hard skills')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Домашняя страница',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.FileField(upload_to='app/admin/skills')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Скиллы',
            },
        ),
    ]
